#!/usr/bin/env python3
import qrcode 
import time
# Data jo QR me encode hoga
data = input("[*]type what you want to encode in the QRCODE: ")

if data == '':
    print("empty string were detected.")
    time.sleep(1)
    print("exiting...")
    time.sleep(1)
    exit()
# This is QR file
qr = qrcode.make(data)

save_name = input("[*]Type file name that will save: ")

if save_name == '':
    print("""file name cannot be empty.
try again...""")
    save_name = input("[*]type again: ")
    if save_name == '':
        print("You fucked up")
        exit()

save_name=f'{save_name}.jpg'

# Image save hoga 
qr.save(save_name)


print(f"QR code {save_name}  saved successfully!")
